const comingSoonLink = {
  href: '#',
  placeholder: true,
  placeholderText: 'Coming soon',
  placeholderTextZh: '即將補上',
};

export const uiCopy = {
  en: {
    brandAria: 'Harry Chan home',
    navHome: 'Home',
    navPortfolio: 'Portfolio',
    navHomework: 'Homework',
    navBlog: 'Blog',
    navAbout: 'About',
    navContact: 'Contact',
    heroEyebrow: 'Harry Chan / HarryWhite-TW',
    heroTitle: 'Building AI-assisted projects into public proof.',
    heroSubtitle:
      'A personal brand gateway for AI applications, web projects, homework showcases, and build logs.',
    heroSignalA: 'AI Applications',
    heroSignalB: 'Web Projects',
    heroSignalC: 'Build Logs',
    ctaProjects: 'View Portfolio',
    ctaHomework: 'Homework Hub',
    ctaNotes: 'Read Notes',
    ctaAbout: 'About Harry',
    heroPanelLabel: 'Brand System',
    heroPanelTitle: 'From class assignments to visible engineering work.',
    heroPanelText: 'Portfolio, homework, notes, and personal direction now live in a clear multi-page structure.',
    gatewayEyebrow: 'Site Gateway',
    gatewayTitle: 'Choose the path that fits your visit.',
    gatewayText: 'The homepage now points to focused pages instead of trying to hold every detail.',
    proofEyebrow: 'Proof Signals',
    metricProjects: 'Project modules',
    metricTracks: 'Skill tracks',
    metricStatic: 'Static + free',
    githubPagesReady: 'GitHub Pages ready',
    featuredEyebrow: 'Featured Preview',
    featuredTitle: 'A few proof points, not the whole archive.',
    featuredText: 'The homepage shows only selected project previews. Full filtering and case studies belong on Portfolio.',
    viewAllProjects: 'View all projects',
    homeworkEyebrow: 'Homework Preview',
    homeworkTitle: 'Teacher-friendly homework is one click away.',
    homeworkText: 'Recent homework remains visible here, while the full centralized index lives on Homework.',
    openHomeworkHub: 'Open Homework Hub',
    notesEyebrow: 'Notes Preview',
    notesTitle: 'Build logs and learning notes stay concise here.',
    notesText: 'Short previews point to the writing hub without turning the homepage into a blog page.',
    openNotes: 'Open Blog / Notes',
    ctaEyebrow: 'Next Step',
    ctaTitle: 'Explore the work, then follow the source.',
    ctaText: 'Start with the Portfolio or Homework Hub, then use GitHub to inspect progress and source code.',
    footerLeft: 'Harry Chan Portfolio / Personal Brand, AI Practice, and Engineering Logs',
    footerRight: '© 2026 Harry Chan. Built with Vite, Tailwind CSS, and Vanilla JavaScript.',
    sourceCode: 'Source Code',
    liveDemo: 'Live Demo',
    notes: 'Notes',
    linksComingSoon: 'Links coming soon',
    statusLabel: 'Status',
    stackLabel: 'Stack',
  },
  zh: {
    brandAria: 'Harry Chan 首頁',
    navHome: '首頁',
    navPortfolio: '作品集',
    navHomework: '作業',
    navBlog: '筆記',
    navAbout: '關於',
    navContact: '聯絡',
    heroEyebrow: 'Harry Chan / HarryWhite-TW',
    heroTitle: '把 AI 輔助專案整理成公開作品證明。',
    heroSubtitle: '這是 Harry Chan 的個人品牌入口，串起 AI 應用、網頁作品、作業展示與 Build Logs。',
    heroSignalA: 'AI 應用',
    heroSignalB: '網頁專案',
    heroSignalC: 'Build Logs',
    ctaProjects: '查看作品集',
    ctaHomework: '作業中心',
    ctaNotes: '閱讀筆記',
    ctaAbout: '關於 Harry',
    heroPanelLabel: '品牌系統',
    heroPanelTitle: '從課堂作業到可展示的工程作品。',
    heroPanelText: '作品集、作業、筆記與個人方向，現在以清楚的多頁架構呈現。',
    gatewayEyebrow: '網站入口',
    gatewayTitle: '依照你的目的選擇入口。',
    gatewayText: '首頁不再塞滿所有細節，而是引導到目的明確的頁面。',
    proofEyebrow: '可信訊號',
    metricProjects: '專案模組',
    metricTracks: '技能軌道',
    metricStatic: '靜態 + 免費',
    githubPagesReady: 'GitHub Pages 就緒',
    featuredEyebrow: '精選預覽',
    featuredTitle: '只留下少量證明，不放完整檔案庫。',
    featuredText: '首頁只展示代表性專案預覽。完整篩選與案例內容會放在 Portfolio。',
    viewAllProjects: '查看所有作品',
    homeworkEyebrow: '作業預覽',
    homeworkTitle: '老師需要的作業中心，只要一個入口。',
    homeworkText: '首頁保留近期作業摘要，完整集中索引則放在 Homework。',
    openHomeworkHub: '打開作業中心',
    notesEyebrow: '筆記預覽',
    notesTitle: 'Build Logs 與學習筆記在首頁保持精簡。',
    notesText: '短篇預覽會引導到寫作中心，不讓首頁變成完整部落格。',
    openNotes: '打開 Blog / Notes',
    ctaEyebrow: '下一步',
    ctaTitle: '先看作品，再追蹤原始碼。',
    ctaText: '可以從 Portfolio 或 Homework Hub 開始，再透過 GitHub 查看進度與原始碼。',
    footerLeft: 'Harry Chan Portfolio / 個人品牌、AI 練習與工程紀錄',
    footerRight: '© 2026 Harry Chan。使用 Vite、Tailwind CSS 與 Vanilla JavaScript 建置。',
    sourceCode: '原始碼',
    liveDemo: '線上展示',
    notes: '筆記',
    linksComingSoon: '連結即將補上',
    statusLabel: '狀態',
    stackLabel: '技術',
  },
};

export const gatewayRoutes = [
  {
    title: 'Portfolio',
    titleZh: '作品集',
    description: 'Selected projects, categories, case-study direction, demos, source links, and build notes.',
    descriptionZh: '整理代表作品、分類、案例方向、展示、原始碼與建置紀錄。',
    href: 'portfolio.html',
    signal: 'Project proof',
    signalZh: '專案證明',
  },
  {
    title: 'Homework',
    titleZh: '作業',
    description: 'Centralized homework browsing for teachers, including HW1-HW5 and future assignments.',
    descriptionZh: '給老師快速檢查的集中式作業入口，包含 HW1-HW5 與未來作業。',
    href: 'homework.html',
    signal: 'Class work',
    signalZh: '課堂成果',
  },
  {
    title: 'Blog / Notes',
    titleZh: 'Blog / 筆記',
    description: 'Build logs, technical notes, AI workflow notes, reflections, and project decisions.',
    descriptionZh: '收錄 Build Logs、技術筆記、AI 工作流筆記、反思與專案決策。',
    href: 'blog.html',
    signal: 'Learning record',
    signalZh: '學習紀錄',
  },
  {
    title: 'About',
    titleZh: '關於',
    description: 'Background, learning path, AI application direction, project philosophy, and roadmap.',
    descriptionZh: '說明背景、學習路線、AI 應用方向、作品理念與成長路線。',
    href: 'about.html',
    signal: 'Personal story',
    signalZh: '個人故事',
  },
];

export const featuredProjects = [
  {
    title: 'Real-time Clock Website',
    titleZh: '即時時鐘網站',
    purpose: 'A first static web assignment focused on time display, layout polish, and GitHub Pages publishing.',
    purposeZh: '第一個靜態網頁作業，重點是時間顯示、版面整理與 GitHub Pages 發布。',
    stack: 'HTML / CSS / JavaScript',
    stackZh: 'HTML / CSS / JavaScript',
    status: 'Published draft',
    statusZh: '已發布草稿',
    links: [
      { label: 'Live Demo', ...comingSoonLink },
      { label: 'Source Code', ...comingSoonLink },
      { label: 'Notes', ...comingSoonLink },
    ],
  },
  {
    title: 'AI Image Generator Homework',
    titleZh: 'AI 圖像生成作業',
    purpose: 'A homework showcase exploring prompt design, generated assets, and responsible presentation.',
    purposeZh: '探索提示設計、生成素材與負責任展示方式的作業展示。',
    stack: 'AI / Prompting / Web UI',
    stackZh: 'AI / Prompting / Web UI',
    status: 'In progress',
    statusZh: '進行中',
    links: [
      { label: 'Live Demo', ...comingSoonLink },
      { label: 'Source Code', ...comingSoonLink },
      { label: 'Notes', ...comingSoonLink },
    ],
  },
  {
    title: 'Input Guardrail Lab',
    titleZh: '輸入防護實驗',
    purpose: 'A small QA-oriented exercise for repeated input patterns and safer app behavior.',
    purposeZh: '針對重複輸入模式與更安全互動行為的小型 QA 練習。',
    stack: 'JavaScript / QA / Testing',
    stackZh: 'JavaScript / QA / Testing',
    status: 'Prototype',
    statusZh: '原型',
    links: [
      { label: 'Live Demo', ...comingSoonLink },
      { label: 'Source Code', ...comingSoonLink },
      { label: 'Notes', ...comingSoonLink },
    ],
  },
];

export const homeworkItems = [
  {
    label: 'HW1',
    title: 'Clock Website',
    titleZh: '時鐘網站',
    description: 'First published web assignment and the foundation for learning GitHub Pages.',
    descriptionZh: '第一個發布到 GitHub Pages 的網頁作業，也是靜態網站發布練習的起點。',
    meta: 'HTML / CSS / JS',
    signal: 'Published practice',
    signalZh: '已發布練習',
  },
  {
    label: 'HW2',
    title: 'AI Visual Practice',
    titleZh: 'AI 視覺練習',
    description: 'Prompting and visual asset workflow for better project presentation.',
    descriptionZh: '練習提示設計與視覺素材流程，讓專案呈現更完整。',
    meta: 'AI / Design',
    signal: 'Visual thinking',
    signalZh: '視覺思考',
  },
  {
    label: 'HW3',
    title: 'Input Guardrail Lab',
    titleZh: '輸入防護實驗',
    description: 'A small engineering exercise around repeated input, testing, and safer app behavior.',
    descriptionZh: '圍繞重複輸入、測試與更安全互動行為的小型工程練習。',
    meta: 'QA / Testing',
    signal: 'Safer behavior',
    signalZh: '安全行為',
  },
];

export const latestNotes = [
  {
    title: 'Why I Built This Portfolio Website',
    titleZh: '為什麼建立這個 Portfolio 網站',
    description: 'A short note about turning learning progress into a public personal brand.',
    descriptionZh: '把學習進度轉化為公開個人品牌的短篇筆記。',
    date: 'Milestone 1',
    dateZh: '里程碑 1',
    link: { label: 'Read note', ...comingSoonLink },
  },
  {
    title: 'How I Created My First GitHub Pages Clock Project',
    titleZh: '如何完成第一個 GitHub Pages 時鐘專案',
    description: 'What I learned from building, testing, and publishing a simple real-time clock.',
    descriptionZh: '從建立、測試到發布簡單即時時鐘專案中學到的事。',
    date: 'HW1 Reflection',
    dateZh: 'HW1 反思',
    link: { label: 'Read note', ...comingSoonLink },
  },
  {
    title: 'From Homework to Portfolio',
    titleZh: '從作業到作品集',
    description: 'How each assignment can become evidence of practical engineering growth.',
    descriptionZh: '每份作業如何成為實際工程能力成長的證明。',
    date: 'Learning Log',
    dateZh: '學習紀錄',
    link: { label: 'Read note', ...comingSoonLink },
  },
];

export const contactLinks = [
  {
    label: 'GitHub',
    href: 'https://github.com/HarryWhite-TW',
    placeholder: false,
  },
  {
    label: 'Contact Page',
    labelZh: '聯絡頁',
    href: 'contact.html',
    placeholder: false,
  },
];
