const comingSoonLink = {
  href: '#',
  placeholder: true,
  placeholderText: 'Coming soon',
  placeholderTextZh: '即將補上',
};

export const uiCopy = {
  en: {
    brandAria: 'Harry Chan home',
    navHome: 'Home',
    navPortfolio: 'Portfolio',
    navHomework: 'Lab',
    navBlog: 'Blog',
    navAbout: 'About',
    navContact: 'Contact',
    heroEyebrow: 'Harry Chan / HarryWhite-TW',
    heroTitle: 'Building useful ideas through AI and engineering.',
    heroSubtitle:
      "Harry Chan's portfolio of AI applications, web experiences, automation experiments, and engineering notes.",
    heroSignalA: 'AI Applications',
    heroSignalB: 'Web Experiences',
    heroSignalC: 'Build Notes',
    ctaProjects: 'View Portfolio',
    ctaHomework: 'Practice Lab',
    ctaNotes: 'Read Notes',
    ctaAbout: 'About Harry',
    heroPanelLabel: 'Current Direction',
    heroPanelTitle: 'Ideas shaped through curiosity, iteration, and delivery.',
    heroPanelText: 'Explore selected work, hands-on practice, and the thinking behind each build.',
    gatewayEyebrow: 'Explore',
    gatewayTitle: 'Start with what you want to discover.',
    gatewayText: 'Browse selected work, hands-on labs, technical notes, and the story behind the journey.',
    proofEyebrow: 'Focus Areas',
    metricProjects: 'Project modules',
    metricTracks: 'Skill tracks',
    metricStatic: 'Static + free',
    githubPagesReady: 'GitHub Pages ready',
    featuredEyebrow: 'Selected Work',
    featuredTitle: 'Selected work that represents my current direction.',
    featuredText: 'A focused selection across AI, web development, automation, and quality-oriented engineering.',
    viewAllProjects: 'View all projects',
    homeworkEyebrow: 'Practice Lab',
    homeworkTitle: 'Hands-on work that shows how I learn and build.',
    homeworkText: 'Selected experiments and coursework are collected here, with the full index available in the Lab.',
    openHomeworkHub: 'Open Practice Lab',
    notesEyebrow: 'Notes Preview',
    notesTitle: 'The thinking behind the work.',
    notesText: 'Build logs, technical reflections, and project decisions captured in short, readable notes.',
    openNotes: 'Open Blog / Notes',
    ctaEyebrow: 'Next Step',
    ctaTitle: 'Explore the work-or the thinking behind it.',
    ctaText: 'Browse selected projects, open the Practice Lab, or follow the source and build history on GitHub.',
    footerLeft: 'Harry Chan Portfolio / Personal Brand, AI Practice, and Engineering Notes',
    footerRight: '© 2026 Harry Chan. Built with Vite, Tailwind CSS, and Vanilla JavaScript.',
    sourceCode: 'Source Code',
    liveDemo: 'Live Demo',
    notes: 'Notes',
    linksComingSoon: 'Links coming soon',
    statusLabel: 'Status',
    stackLabel: 'Stack',
  },
  zh: {
    brandAria: 'Harry Chan 首頁',
    navHome: '首頁',
    navPortfolio: '作品集',
    navHomework: '實作',
    navBlog: '筆記',
    navAbout: '關於',
    navContact: '聯絡',
    heroEyebrow: 'Harry Chan / HarryWhite-TW',
    heroTitle: '用 AI 與工程實作，打造值得被看見的作品。',
    heroSubtitle: '這裡收錄 Harry Chan 的 AI 應用、網頁體驗、自動化實驗與工程紀錄。',
    heroSignalA: 'AI 應用',
    heroSignalB: '網頁體驗',
    heroSignalC: '工程筆記',
    ctaProjects: '查看作品集',
    ctaHomework: '實作紀錄',
    ctaNotes: '閱讀筆記',
    ctaAbout: '關於 Harry',
    heroPanelLabel: '目前方向',
    heroPanelTitle: '以好奇、迭代與交付，讓想法成為作品。',
    heroPanelText: '探索精選作品、技術實作，以及每次建置背後的思考。',
    gatewayEyebrow: '探索網站',
    gatewayTitle: '從你想了解的方向開始。',
    gatewayText: '瀏覽精選作品、實作紀錄、技術筆記與成長脈絡。',
    proofEyebrow: '發展重點',
    metricProjects: '專案模組',
    metricTracks: '技能軌道',
    metricStatic: '靜態免費',
    githubPagesReady: 'GitHub Pages 就緒',
    featuredEyebrow: '精選作品',
    featuredTitle: '精選作品，呈現目前的技術方向。',
    featuredText: '聚焦展示 AI、網頁開發、自動化與品質工程方向的代表作品。',
    viewAllProjects: '查看所有作品',
    homeworkEyebrow: '實作紀錄',
    homeworkTitle: '用實作呈現我如何學習與建造。',
    homeworkText: '這裡整理部分練習與課程專案，完整內容可在實作頁查看。',
    openHomeworkHub: '開啟實作頁',
    notesEyebrow: '筆記預覽',
    notesTitle: '作品背後的思考。',
    notesText: '以短篇筆記記錄建置歷程、技術反思與專案決策。',
    openNotes: '開啟筆記',
    ctaEyebrow: '下一步',
    ctaTitle: '看作品，也看作品背後的思考。',
    ctaText: '瀏覽精選作品、實作紀錄，或前往 GitHub 查看原始碼與建置歷程。',
    footerLeft: 'Harry Chan 作品集 / 個人品牌、AI 實作與工程筆記',
    footerRight: '© 2026 Harry Chan. 使用 Vite、Tailwind CSS 與 Vanilla JavaScript 建置。',
    sourceCode: '原始碼',
    liveDemo: '線上展示',
    notes: '筆記',
    linksComingSoon: '連結即將補上',
    statusLabel: '狀態',
    stackLabel: '技術',
  },
};

export const gatewayRoutes = [
  {
    title: 'Portfolio',
    titleZh: '作品集',
    description: 'Selected AI, web, automation, and QA-oriented projects with demos, source links, and build notes.',
    descriptionZh: '精選 AI、網頁、自動化與品質工程方向的作品，包含展示、原始碼與建置筆記。',
    href: 'portfolio.html',
    signal: 'Selected work',
    signalZh: '精選作品',
  },
  {
    title: 'Practice Lab',
    titleZh: '實作',
    description: 'Hands-on experiments, coursework, and engineering exercises shaped through learning by building.',
    descriptionZh: '整理實作實驗、課程專案與工程練習，呈現邊做邊學的累積。',
    href: 'homework.html',
    signal: 'Hands-on practice',
    signalZh: '實作紀錄',
  },
  {
    title: 'Blog / Notes',
    titleZh: 'Blog / 筆記',
    description: 'Build logs, technical notes, AI workflow notes, reflections, and project decisions.',
    descriptionZh: '建置紀錄、技術筆記、AI 工作流、反思與專案決策。',
    href: 'blog.html',
    signal: 'Build notes',
    signalZh: '工程筆記',
  },
  {
    title: 'About',
    titleZh: '關於',
    description: 'Background, current direction, working principles, learning path, and future development.',
    descriptionZh: '背景、目前方向、工作原則、學習路徑與未來發展。',
    href: 'about.html',
    signal: 'Personal direction',
    signalZh: '個人方向',
  },
];

export const featuredProjects = [
  {
    title: 'Real-time Clock Website',
    titleZh: '即時時鐘網站',
    purpose: 'A compact web interface focused on real-time display, layout clarity, and GitHub Pages delivery.',
    purposeZh: '聚焦即時顯示、版面清晰度與 GitHub Pages 發布的精簡網頁介面。',
    stack: 'HTML / CSS / JavaScript',
    stackZh: 'HTML / CSS / JavaScript',
    status: 'Published draft',
    statusZh: '已發布草稿',
    links: [
      { label: 'Live Demo', ...comingSoonLink },
      { label: 'Source Code', ...comingSoonLink },
      { label: 'Notes', ...comingSoonLink },
    ],
  },
  {
    title: 'AI Visual Generation Study',
    titleZh: 'AI 視覺生成研究',
    purpose: 'An exploration of prompt design, generated visual assets, and responsible presentation.',
    purposeZh: '探索提示設計、生成式視覺素材與負責任呈現方式的實作。',
    stack: 'AI / Prompting / Web UI',
    stackZh: 'AI / Prompting / Web UI',
    status: 'In progress',
    statusZh: '進行中',
    links: [
      { label: 'Live Demo', ...comingSoonLink },
      { label: 'Source Code', ...comingSoonLink },
      { label: 'Notes', ...comingSoonLink },
    ],
  },
  {
    title: 'Input Guardrail Lab',
    titleZh: '輸入防護實驗',
    purpose: 'A QA-oriented engineering exercise for repeated input patterns, validation, and safer app behavior.',
    purposeZh: '以 QA 與工程品質為核心，練習重複輸入、驗證流程與更安全的應用行為。',
    stack: 'JavaScript / QA / Testing',
    stackZh: 'JavaScript / QA / Testing',
    status: 'Prototype',
    statusZh: '原型',
    links: [
      { label: 'Live Demo', ...comingSoonLink },
      { label: 'Source Code', ...comingSoonLink },
      { label: 'Notes', ...comingSoonLink },
    ],
  },
];

export const homeworkItems = [
  {
    label: 'HW1',
    title: 'Clock Website',
    titleZh: '時鐘網站',
    description: 'A first static web build for practicing layout, JavaScript timing, and publishing.',
    descriptionZh: '第一個靜態網頁實作，用來練習版面、JavaScript 時間處理與發布流程。',
    meta: 'HTML / CSS / JS',
    signal: 'Published practice',
    signalZh: '已發布實作',
  },
  {
    label: 'HW2',
    title: 'AI Visual Generation Study',
    titleZh: 'AI 視覺生成研究',
    description: 'Prompting and visual asset workflow practice for clearer project presentation.',
    descriptionZh: '練習提示設計與視覺素材工作流，讓專案呈現更清楚。',
    meta: 'AI / Design',
    signal: 'Visual workflow',
    signalZh: '視覺流程',
  },
  {
    label: 'HW3',
    title: 'Input Guardrail Lab',
    titleZh: '輸入防護實驗',
    description: 'A small engineering exercise around repeated input, testing, and safer app behavior.',
    descriptionZh: '圍繞重複輸入、測試與更安全的應用行為所做的小型工程練習。',
    meta: 'QA / Testing',
    signal: 'Safer behavior',
    signalZh: '安全行為',
  },
];

export const latestNotes = [
  {
    title: 'Why I Built This Portfolio Website',
    titleZh: '為什麼建立這個作品集網站',
    description: 'A short note about turning learning progress into a public personal brand.',
    descriptionZh: '記錄如何把學習進度整理成公開的個人品牌。',
    date: 'Origin Note',
    dateZh: '起點筆記',
    link: { label: 'Read note', ...comingSoonLink },
  },
  {
    title: 'How I Created My First GitHub Pages Clock Project',
    titleZh: '第一個 GitHub Pages 時鐘專案',
    description: 'What I learned from building, testing, and publishing a simple real-time clock.',
    descriptionZh: '從建置、測試到發布即時時鐘專案的學習紀錄。',
    date: 'Build Log',
    dateZh: '建置紀錄',
    link: { label: 'Read note', ...comingSoonLink },
  },
  {
    title: 'From Practice to Portfolio',
    titleZh: '從實作走向作品集',
    description: 'How small exercises can become visible signs of practical engineering growth.',
    descriptionZh: '整理小型練習如何逐步累積成可被看見的工程成長。',
    date: 'Learning Log',
    dateZh: '學習紀錄',
    link: { label: 'Read note', ...comingSoonLink },
  },
];

export const contactLinks = [
  {
    label: 'GitHub',
    href: 'https://github.com/HarryWhite-TW',
    placeholder: false,
  },
  {
    label: 'Contact Page',
    labelZh: '聯絡頁',
    href: 'contact.html',
    placeholder: false,
  },
];
