const comingSoonLink = {
  href: '#',
  placeholder: true,
  placeholderText: 'Coming soon',
  placeholderTextZh: '即將補上',
};

export const uiCopy = {
  en: {
    brandAria: 'Harry Chan home',
    navHome: 'Home',
    navPortfolio: 'Portfolio',
    navHomework: 'Homework',
    navBlog: 'Blog',
    navAbout: 'About',
    navContact: 'Contact',
    heroEyebrow: 'AI Mission Control / Project-Based Engineering',
    heroTitleA: 'Building',
    heroTitleB: 'AI, Web, and Automation',
    heroTitleC: 'Projects',
    heroSubtitle:
      'I am learning AI application development through mission-style homework, project launches, build logs, and engineering practice.',
    signalStatic: 'Static Site',
    signalAi: 'AI Practice',
    signalStory: 'Mission Logs',
    ctaProjects: 'View Projects',
    ctaHomework: 'Explore Homework',
    metricProjects: 'Launch modules',
    metricTracks: 'Skill orbits',
    metricStatic: 'Static + free',
    githubPagesReady: 'GitHub Pages ready',
    missionLabel: 'Active Mission',
    missionTitle: 'Portfolio v1 is online: homework signals are becoming public project launches.',
    missionPrototype: 'Prototype',
    missionPrototypeText: 'Build small, visible apps.',
    missionDocument: 'Document',
    missionDocumentText: 'Turn each assignment into a mission log.',
    featuredEyebrow: 'Launch Modules',
    featuredTitle: 'Project Work, Presented Like Product Work',
    featuredText:
      'Each build gets a mission brief, signal status, stack, and next action so homework reads like real engineering progress.',
    homeworkEyebrow: 'Homework Signals',
    homeworkTitle: 'A Learning Galaxy, Not a Link Dump',
    homeworkText:
      'Assignments orbit the portfolio as visible practice signals, each connected to a skill, tool, or engineering habit.',
    galaxyCore: 'HW',
    galaxyCoreText: 'Signal Hub',
    roadmapEyebrow: 'Launch Sequence',
    roadmapTitle: 'Roadmap From Learner to Builder',
    roadmapText:
      'The roadmap shows the skill sequence behind every project launch: learn, build, test, document, and publish.',
    notesEyebrow: 'Build Logs',
    notesTitle: 'Learning Notes With a Mission-Log Feel',
    notesText:
      'Short reflections connect assignments, tools, decisions, and the habits behind stronger engineering work.',
    ctaEyebrow: 'Final Launch Panel',
    ctaTitle: 'Ready to turn the next homework into a stronger project mission.',
    footerLeft: 'Harry Chan Portfolio / AI Mission Control and Engineering Practice',
    footerRight: '© 2026 Harry Chan. Built with Vite, Tailwind CSS, and Vanilla JavaScript.',
    sourceCode: 'Source Code',
    liveDemo: 'Live Demo',
    notes: 'Notes',
    linksComingSoon: 'Links coming soon',
  },
  zh: {
    brandAria: 'Harry Chan 首頁',
    navHome: '首頁',
    navPortfolio: '作品集',
    navHomework: '作業',
    navBlog: '筆記',
    navAbout: '關於',
    navContact: '聯絡',
    heroEyebrow: 'AI 任務控制台 / 專案式工程學習',
    heroTitleA: '打造',
    heroTitleB: 'AI、網站與自動化',
    heroTitleC: '專案',
    heroSubtitle: '我透過任務式作業、專案發布、Build Logs 與工程練習，學習 AI 應用開發。',
    signalStatic: '靜態網站',
    signalAi: 'AI 練習',
    signalStory: '任務紀錄',
    ctaProjects: '查看作品',
    ctaHomework: '瀏覽作業',
    metricProjects: '發布模組',
    metricTracks: '技能軌道',
    metricStatic: '靜態 + 免費',
    githubPagesReady: 'GitHub Pages 就緒',
    missionLabel: '目前任務',
    missionTitle: 'Portfolio v1 已上線：課堂作業正在轉化為公開專案成果。',
    missionPrototype: '原型',
    missionPrototypeText: '建立小而可見的應用。',
    missionDocument: '紀錄',
    missionDocumentText: '把每份作業整理成任務紀錄。',
    featuredEyebrow: '發布模組',
    featuredTitle: '用產品展示方式呈現專案',
    featuredText: '每個作品都有任務簡介、狀態、技術棧與下一步，讓作業更像真實工程進展。',
    homeworkEyebrow: '作業訊號',
    homeworkTitle: '學習星系，而不是連結清單',
    homeworkText: '作業以可見的練習訊號呈現，並連結到技能、工具或工程習慣。',
    galaxyCore: 'HW',
    galaxyCoreText: '作業中心',
    roadmapEyebrow: '發布順序',
    roadmapTitle: '從學習者到建造者的路線圖',
    roadmapText: '路線圖呈現每次專案發布背後的技能順序：學習、建置、測試、紀錄與發布。',
    notesEyebrow: 'Build Logs',
    notesTitle: '具有任務紀錄感的學習筆記',
    notesText: '短篇反思串起作業、工具、決策，以及讓工程能力變強的習慣。',
    ctaEyebrow: '最終發布面板',
    ctaTitle: '準備把下一份作業變成更完整的專案任務。',
    footerLeft: 'Harry Chan Portfolio / AI 任務控制台與工程練習',
    footerRight: '© 2026 Harry Chan。使用 Vite、Tailwind CSS 與 Vanilla JavaScript 建置。',
    sourceCode: '原始碼',
    liveDemo: '線上展示',
    notes: '筆記',
    linksComingSoon: '連結即將補上',
  },
};

export const featuredProjects = [
  {
    title: 'Real-time Clock Website',
    titleZh: '即時時鐘網站',
    description: 'A GitHub Pages clock project focused on time display, layout polish, and publishing a small web app.',
    descriptionZh: '以時間顯示、版面整理與 GitHub Pages 發布為重點的小型網站作業。',
    tags: ['HTML', 'CSS', 'JavaScript', 'GitHub Pages'],
    tagsZh: ['HTML', 'CSS', 'JavaScript', 'GitHub Pages'],
    status: 'Published draft',
    statusZh: '已發布草稿',
    accent: 'cyan',
    icon: 'CLK',
    metric: 'Live time UI',
    metricZh: '即時時間介面',
    links: [
      { label: 'Live Demo', ...comingSoonLink },
      { label: 'Source Code', ...comingSoonLink },
      { label: 'Notes', ...comingSoonLink },
    ],
    placeholder: true,
  },
  {
    title: 'AI Image Generator Homework',
    titleZh: 'AI 圖像生成作業',
    description: 'A homework showcase exploring prompt design, generated visual assets, and responsible presentation.',
    descriptionZh: '探索提示設計、生成式視覺素材與負責任展示方式的作業展示。',
    tags: ['AI', 'Prompting', 'Web UI'],
    tagsZh: ['AI', 'Prompting', 'Web UI'],
    status: 'In progress',
    statusZh: '進行中',
    accent: 'violet',
    icon: 'IMG',
    metric: 'Prompt workflow',
    metricZh: '提示工作流',
    links: [
      { label: 'Live Demo', ...comingSoonLink },
      { label: 'Source Code', ...comingSoonLink },
      { label: 'Notes', ...comingSoonLink },
    ],
    placeholder: true,
  },
  {
    title: 'Reverb / Echo Input Guardrail Project',
    titleZh: '重複輸入 Guardrail 專案',
    description: 'A project about detecting repeated user input patterns and thinking through safer AI interaction design.',
    descriptionZh: '練習偵測重複輸入模式，並思考更安全 AI 互動設計的小型專案。',
    tags: ['AI Safety', 'JavaScript', 'QA / Testing'],
    tagsZh: ['AI Safety', 'JavaScript', 'QA / Testing'],
    status: 'Prototype',
    statusZh: '原型',
    accent: 'warm',
    icon: 'QA',
    metric: 'Input checks',
    metricZh: '輸入檢查',
    links: [
      { label: 'Live Demo', ...comingSoonLink },
      { label: 'Source Code', ...comingSoonLink },
      { label: 'Notes', ...comingSoonLink },
    ],
    placeholder: true,
  },
];

export const homeworkItems = [
  {
    label: 'HW1',
    title: 'Clock Website',
    titleZh: '時鐘網站',
    description: 'First published web assignment and the foundation for learning GitHub Pages.',
    descriptionZh: '第一個發布到 GitHub Pages 的網頁作業，也是靜態網站發布練習的起點。',
    meta: 'HTML / CSS / JS',
    signal: 'Published practice',
    signalZh: '已發布練習',
  },
  {
    label: 'HW2',
    title: 'AI Visual Practice',
    titleZh: 'AI 視覺練習',
    description: 'Prompting and visual asset workflow for better project presentation.',
    descriptionZh: '練習提示設計與視覺素材流程，讓專案呈現更完整。',
    meta: 'AI / Design',
    signal: 'Visual thinking',
    signalZh: '視覺思考',
  },
  {
    label: 'HW3',
    title: 'Input Guardrail Lab',
    titleZh: '輸入防護實驗',
    description: 'A small engineering exercise around repeated input, testing, and safer app behavior.',
    descriptionZh: '圍繞重複輸入、測試與更安全互動行為的小型工程練習。',
    meta: 'QA / Automation',
    signal: 'Safer behavior',
    signalZh: '安全行為',
  },
];

export const roadmapItems = [
  {
    title: 'AI Application',
    titleZh: 'AI 應用',
    description: 'Build useful AI-assisted tools and explain how they work.',
    descriptionZh: '建立有用的 AI 輔助工具，並清楚說明運作方式。',
    signal: 'Prompts + product thinking',
    signalZh: '提示 + 產品思考',
  },
  {
    title: 'Web Development',
    titleZh: '網站開發',
    description: 'Practice responsive interfaces with HTML, CSS, Tailwind, and JavaScript.',
    descriptionZh: '使用 HTML、CSS、Tailwind 與 JavaScript 練習響應式介面。',
    signal: 'Interface foundations',
    signalZh: '介面基礎',
  },
  {
    title: 'GitHub Pages',
    titleZh: 'GitHub Pages',
    description: 'Publish static projects and document deployment steps clearly.',
    descriptionZh: '發布靜態專案，並清楚紀錄部署步驟。',
    signal: 'Public delivery',
    signalZh: '公開交付',
  },
  {
    title: 'QA / Testing',
    titleZh: 'QA / 測試',
    description: 'Check layouts, links, edge cases, and user flows before sharing.',
    descriptionZh: '分享前檢查版面、連結、邊界情境與使用流程。',
    signal: 'Quality habits',
    signalZh: '品質習慣',
  },
  {
    title: 'Automation',
    titleZh: '自動化',
    description: 'Use scripts and AI tools to speed up repeatable engineering work.',
    descriptionZh: '使用腳本與 AI 工具加速可重複的工程工作。',
    signal: 'Repeatable workflow',
    signalZh: '可重複流程',
  },
];

export const latestNotes = [
  {
    title: 'Why I Built This Portfolio Website',
    titleZh: '為什麼建立這個 Portfolio 網站',
    description: 'A short note about turning learning progress into a public personal brand.',
    descriptionZh: '把學習進度轉化為公開個人品牌的短篇筆記。',
    date: 'Milestone 1',
    dateZh: '里程碑 1',
    link: { label: 'Read note', ...comingSoonLink },
  },
  {
    title: 'How I Created My First GitHub Pages Clock Project',
    titleZh: '如何完成第一個 GitHub Pages 時鐘專案',
    description: 'What I learned from building, testing, and publishing a simple real-time clock.',
    descriptionZh: '從建立、測試到發布簡單即時時鐘專案中學到的事。',
    date: 'HW1 Reflection',
    dateZh: 'HW1 反思',
    link: { label: 'Read note', ...comingSoonLink },
  },
  {
    title: 'From Homework to Portfolio: My AI Learning Journey',
    titleZh: '從作業到作品集：我的 AI 學習旅程',
    description: 'How each assignment can become evidence of practical engineering growth.',
    descriptionZh: '每份作業如何成為實際工程能力成長的證明。',
    date: 'Learning Log',
    dateZh: '學習紀錄',
    link: { label: 'Read note', ...comingSoonLink },
  },
];

export const contactLinks = [
  {
    label: 'GitHub',
    href: 'https://github.com/HarryWhite-TW',
    placeholder: false,
  },
  {
    label: 'Email Placeholder',
    labelZh: 'Email 預留位置',
    href: '#',
    placeholder: true,
    placeholderText: 'Placeholder',
    placeholderTextZh: '預留位置',
  },
  {
    label: 'Portfolio Link',
    labelZh: '作品集連結',
    href: '#',
    placeholder: true,
    placeholderText: 'Coming soon',
    placeholderTextZh: '即將補上',
  },
];
